# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
  - CollinErickson/SMED-Code
  - CollinErickson/IGP
  - CollinErickson/sFFLHD
  - CollinErickson/TestFunctions
  - CollinErickson/GauPro

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'version'
